### ISSUE TITLE
Schnittstellenrealisierung: api/subject/deactivate

### ISSUE THREAD

**Issue by bzenz** [bzenz/GradeMe#60]
Ein Fach löschen.

**Noch zu klären:** Was passiert mit den Referenzen auf dieses Fach? 
--> es wird ein Flag auf deactivated gesetzt, sodass keine neuen Kurse mit diesem Fach erstellt werden können, aber das Fach in der DB trotzdem noch existiert.

**Comment by Blackie11elf** [comment]
Wenn es Referenzen auf dieses Fach gibt, sollte es beim löschen angezeigt werden. Heißt wenn die Schnittstelle aufgerufen wird, sollte im Backend zuerst geprüft werden, ob es noch Referenzen auf dieses Fach gibt. Falls ja, sollte dies als Antwort zurückgegeben werden, sodass das Fach nicht gelöscht werden kann. Dem Nutzer sollte daraufhin angezeigt werden welche Kurse noch dieses Fach "benutzen".

Später könnte man möglicherweise eine Option einbauen, dass dieses Fach ab dem Zeitpunkt der Löschung nur nicht mehr neu verwenden werden kann in einem Kurs, aber bestehende Kurse trotzdem noch auf dieses Fach referiere können.
